### ISSUE TITLE
missing functions for calibrations

### ISSUE THREAD

**Issue by hellowangqian** [RasmusHaugaard/peg-in-hole-visual-servoing#1]
Dear author,
Thanks for sharing the great work! I'm a fresher in robotic control and learned a lot from this repository. When I try to understand the code given in the readme, some functions seem to be missing: 
```
state[peg_robot_base] = get_table_peg_base_calibration()
state[cams_robot_base] = get_table_cams_base_calibration()
state[cam_a] = get_tcp_cam_a_calibration()
state[cam_b] = get_tcp_cam_b_calibration()
Ks, dist_coeffs = get_camera_intrinsic_calibrations()
```
Could you please advise how/where to get these get_xxx functions? Many thanks in advance.

**Comment by hellowangqian** [comment]
Also, I cannot find the method `peg_in_hole_visual_servoing.config_from_demonstration()`, is there anything related to this missing?

**Comment by rasmushaugaard** [comment]
Hi 

The get_X_calibration are dummy functions. This package doesn't provide tools for calibrations.

`peg_in_hole_visual_servoing.config_from_demonstration` is [here](https://github.com/rasmushaugaard/peg-in-hole-visual-servoing/blob/master/peg_in_hole_visual_servoing/servo_configure.py)

BR Rasmus

**Comment by hellowangqian** [comment]
Many thanks, your kind reply is very helpful.
