### ISSUE TITLE
How to install ur_control?

### ISSUE THREAD

**Issue by Jiaviz** [RasmusHaugaard/peg-in-hole-visual-servoing#2]
I failed to find this the `ur_control` lib. Thanks a lot if you could provide some datiled information about this lib.

**Comment by rasmushaugaard** [comment]
I haven't used it since, but here is the code from that repo: [ur_control.zip](https://github.com/rasmushaugaard/peg-in-hole-visual-servoing/files/15188200/ur_control.zip)

**Comment by Jiaviz** [comment]
> I haven't used it since, but here is the code from that repo: [ur_control.zip](https://github.com/rasmushaugaard/peg-in-hole-visual-servoing/files/15188200/ur_control.zip)

Thanks a lot!
